[tool.poetry]
name = "stx-blog"
version = "0.1.0"
description = ""
authors = ["Bartosz Brozyna <bartosz.brozyna@stxnext.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^7.2.0"
pytest-playwright = "^0.3.0"
pytest-base-url = "^2.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
